language: rust
rust:
  - 1.31.0
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true
script:
  - cargo build --verbose
  - cargo test --verbose
  - rustup install nightly
  - rustup component add rustfmt --toolchain nightly
  - cargo +nightly fmt --all -- --check
